vlib work
vmap work work
vcom -reportprogress 300 -work work ise/ipcore_dir/mult_acc_pwrmon.vhd
vcom -reportprogress 300 -work work ise/ipcore_dir/fifo_dock_comms.vhd
vcom -reportprogress 300 -work work ise/ipcore_dir/fifo_8x16.vhd
vcom -reportprogress 300 -work work ise/ipcore_dir/fifo_uart.vhd
vcom -reportprogress 300 -work work ise/ipcore_dir/fifo_jam_eng.vhd
vcom -reportprogress 300 -work work ise/ipcore_dir/blk_mem_dblr_att.vhd
vcom -reportprogress 300 -work work ise/ipcore_dir/blk_mem_jam_eng.vhd
vcom -reportprogress 300 -work work ise/ipcore_dir/uart_clk.vhd
vcom -reportprogress 300 -work work ise/ipcore_dir/pll_reg_clk.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/reg_ctrl/reg_pkg.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/reg_ctrl/reg_miso_mux6.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/reg_ctrl/reg_mosi_dq.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/delay/slv_delay.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/delay/unsigned_delay.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/synchroniser/slv_synchroniser.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/i2c_master/i2c_master_bit_ctrl.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/i2c_master/i2c_master_byte_ctrl.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/rs485_ctrl/rs485_ctrl.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/lattice/RD1011_rev01.5/rxcver.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/lattice/RD1011_rev01.5/txmitt.vhd
vcom -reportprogress 300 -work work submodules/vhdl_general/uart/uart.vhd
vcom -reportprogress 300 -work work src/mercury_pkg.vhd
vcom -reportprogress 300 -work work src/mercury_source_board_version.vhd
vcom -reportprogress 300 -work work src/i2c_dac_cmd_ctrl.vhd
vcom -reportprogress 300 -work work src/i2c_master_cmd_ctrl.vhd
vcom -reportprogress 300 -work work src/i2c_master_top.vhd
vcom -reportprogress 300 -work work src/pwr_mon_block_avg.vhd
vcom -reportprogress 300 -work work src/pwr_mon_block_avg_tb.vhd
vcom -reportprogress 300 -work work src/pwr_mon_moving_avg.vhd
vcom -reportprogress 300 -work work src/pwr_mon_moving_avg_tb.vhd
vcom -reportprogress 300 -work work src/pwr_mon_spi_master.vhd
vcom -reportprogress 300 -work work src/pwr_mon_capture.vhd
vcom -reportprogress 300 -work work src/pwr_mon_capture_tb.vhd
vcom -reportprogress 300 -work work src/pwr_mon_top.vhd
vcom -reportprogress 300 -work work src/dock_packet_gen.vhd
vcom -reportprogress 300 -work work src/dock_packet_decode.vhd
vcom -reportprogress 300 -work work src/dock_comms.vhd
vcom -reportprogress 300 -work work src/vswr_miso_mux.vhd
vcom -reportprogress 300 -work work src/pa_management.vhd
vcom -reportprogress 300 -work work src/cpu_spi_slave.vhd
vcom -reportprogress 300 -work work src/general_registers.vhd
vcom -reportprogress 300 -work work src/dac_ctrl.vhd
vcom -reportprogress 300 -work work src/dds_interface.vhd
vcom -reportprogress 300 -work work src/synth_interface.vhd
vcom -reportprogress 300 -work work src/rf_ctrl.vhd
vcom -reportprogress 300 -work work src/blank_ctrl.vhd
vcom -reportprogress 300 -work work src/prbs_gen.vhd
vcom -reportprogress 300 -work work src/jam_engine_core.vhd
vcom -reportprogress 300 -work work src/jam_engine_top.vhd
vcom -reportprogress 300 -work work src/vswr_engine.vhd
vcom -reportprogress 300 -work work src/pps_sync.vhd
vcom -reportprogress 300 -work work src/interrupt_controller.vhd
vcom -reportprogress 300 -work work src/mercury_clocks.vhd
vcom -reportprogress 300 -work work src/mercury_source_board_top.vhd
