# Compile IP cores
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/pll_reg_clk.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/blk_mem_jam_eng.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/fifo_jam_eng.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/blk_mem_dblr_att.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/fifo_8x16.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/fifo_uart.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/fifo_drm_if.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/uart_clk.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/fifo_dock_comms.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/mult_acc_pwrmon.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/mult_freq_trim.vhd
vcom -nowarn DAGGEN_0523 ../../ise/ipcore_dir/mult_add_pps_sync.vhd
